fichier=open("data/journal.txt", "w+", encoding="utf-8")
fichier.write("Jour 1 : Introduction\n")
fichier.write("Jour 2 : Variables\n")
fichier.write("Jour 3 : Conditions\n")
fichier.write("Jour 4 : Boucles\n")
fichier.write("Jour 5 : Fonctions\n")
fichier.write("Jour 6 : Listes\n")
fichier.write("Jour 7 : Dictionnaires\n")
fichier.write("Jour 8 : Tuples\n")
fichier.write("Jour 9 : Ensembles\n")
fichier.write("Jour 10 : Manipulation de fichiers texte\n")
fichier.write("Jour 11 : Manipulation de fichiers CSV\n")
fichier.write("Jour 12 : Manipulation de fichiers JSON\n")
fichier.write("Jour 13 : NumPy - Sauvegarde de tableaux\n")
fichier.write("Jour 14 : NumPy - Chargement de tableaux\n")
fichier.write("Jour 15 : Graphiques avec matplotlib\n")
fichier.write("Jour 16 : Résolution d'erreurs JSON\n")
fichier.write("Jour 17 : Gestion des exceptions en Python\n")
fichier.write("Jour 18 : Écriture avancée avec format()\n")
fichier.write("Jour 19 : Encodage de fichiers texte\n")
fichier.write("Jour 20 : Conclusion et révision\n")
fichier.close()